### ISSUE TITLE
Does not work with profiles that assume a role in a different account

### ISSUE THREAD

**Issue by coyoteecd** [maasglobal/serverless-deployment-manager#10]
Having a profile entry in the serverless.yml file that assumes a role in another AWS account triggers validation errors when configured to check for allowed accountIds (as per readme). It looks like the plugin validates against my default AWS account ID configured in .aws/credentials, and not the deployment account id that is used in the actual deploy.

```
# serverless.yml
plugins:
  - serverless-deployment-manager

provider:
  name: aws
  profile: my-aws-credential-profile

custom:
  deployment:
    - stage: dev
      accountId: [deployment account ID]
```

Running `serverless validate` or `serverless deploy` fails, complaining that I am not allowed to deploy to [my default account ID]. That's wrong; validation should take into account the profile setting and extract the target account from there.
